Nota de desempleo
davidmacer/desempleo-enoa pull request #1
Opened 2021-05-31 06:57 UTC by nepito

Aquí escribimos la primera versión de la transcripción de la [nota de Milenio](https://www.milenio.com/negocios/aumenta-desempleo-en-mexico-durante-el-primer-trimestre-inegi).

2021-06-03 20:11 UTC, nepito commented on src/desempleo-enoa.Rmd
> +En el primer trimestre de 2021, se registró una disminución de 1.6 millones de personas en la Población Económicamente Activa (PEA), que representa la fuerza laboral del país, en comparación con el m
¿Cómo podremos meter los valores como variables y después los cambiamos?

Como para que lo pudiéramos dejar algo así:
`al pasar de {primer_trimetres_agno_pasado} millones a{primer_trimetres_agno_presente} millones`

2021-06-05 03:56 UTC, nepito reviewed
Ya agregué a R y las paqueterías de R al Dockerfile.

2021-06-05 03:56 UTC, nepito commented on src/desempleo-enoa.Rmd
> +library(tweetrmd)
@davidmacer ya agregué un Makefile y actualicé el Dockerfile, pero estoy teniendo algún problema para generar el html. El problema tiene que ver con la renderización de los twitters. Así que para generar el html comento las líneas de código que empiezan así `tweet_screenshot(tweet_url`.

Hasta el momento ya agregué los datos para primera sección. Te aviso cuando termine con el resto de los datos de la nota.

- Loco creo que ya no necesitaremos los archivos que están en la carpeta `reports` ¿Crees que podemos eliminarlos?

2021-06-17 22:17 UTC, davidmacer commented on src/desempleo-enoa.Rmd
> +library(tweetrmd)
Me parece que ya eliminaste la carpeta `reports` y su contenido, pero sí era necesario eliminarlos. Gracias por hacerlo, loco.

2021-06-19 06:03 UTC, nepito commented
@davidmacer parece que ya quedó el cotorreo del Dockerfile. Ya deberías de poder correr `make docs/index.html` desde el contenedor. 

También agregué la primera versión del _actions_. Para que funcione necesitará el token del inegi:
![image](https://user-images.githubusercontent.com/35377740/122632681-4e701f80-d089-11eb-82b1-6e2aed0987e3.png)

2021-06-21 22:01 UTC, davidmacer requested changes

2021-06-21 22:01 UTC, davidmacer commented on Dockerfile
> +RUN echo 'exec -a "$0" "$HERE/chrome" "$@" --no-sandbox' >> exit.txt && chmod +x exit.txt
Por ahí está un `-a`, pero no sé si es una abreviatura. Si es abreviatura, conviene ponerla con su nombre largo.

2021-06-22 02:35 UTC, nepito commented on Dockerfile
> +RUN echo 'exec -a "$0" "$HERE/chrome" "$@" --no-sandbox' >> exit.txt && chmod +x exit.txt
Parece que ni tiene versión larga:
![image](https://user-images.githubusercontent.com/35377740/122853844-b3b15400-d2c7-11eb-8a31-1471cbf82d63.png)

Esas dos líneas son lo para  agregar el `--no-sandbox`, pero no estoy seguro ni de para qué ni qué significa.

2021-06-22 20:23 UTC, davidmacer commented
> @davidmacer parece que ya quedó el cotorreo del Dockerfile. Ya deberías de poder correr `make docs/index.html` desde el contenedor.
> 
> También agregué la primera versión del _actions_. Para que funcione necesitará el token del inegi:
> ![image](https://user-images.githubusercontent.com/35377740/122632681-4e701f80-d089-11eb-82b1-6e2aed0987e3.png)

Esto ya quedó. Solamente me hace falta hacer algún _commit_ y verificar que sí me esté funcionando. ¡Gracias por checarlo, loco!

2021-06-22 20:24 UTC, davidmacer commented on Dockerfile
> +RUN echo 'exec -a "$0" "$HERE/chrome" "$@" --no-sandbox' >> exit.txt && chmod +x exit.txt
¡Excelente! Se facilita que no tenga versión larga, ni para dónde hacerse.

2021-06-22 20:27 UTC, davidmacer approved these changes
Las revisiones por mi parte ya quedaron. Por ahí me encontré un paquete, `rtweet`, que revisaré para ver si funciona y agregar los twits de otra manera.

2021-06-22 23:04 UTC, nepito commented
> Las revisiones por mi parte ya quedaron. Por ahí me encontré un paquete, `rtweet`, que revisaré para ver si funciona y agregar los twits de otra manera.

¿Ya probaste si te funciona ahora? A mí ya me está corriendo desde el Dockerfile. Pero aun no está andando el _actions_ 🤔

2021-06-22 23:23 UTC, merged

2021-06-23 01:45 UTC, davidmacer commented
> > Las revisiones por mi parte ya quedaron. Por ahí me encontré un paquete, `rtweet`, que revisaré para ver si funciona y agregar los twits de otra manera.
> 
> ¿Ya probaste si te funciona ahora? A mí ya me está corriendo desde el Dockerfile. Pero aun no está andando el _actions_  Supongo que debo de tener alguna falta de ortografía por ahí jajajaja

El make dentro del contenedor está creando el `index.html`, pero estoy teniendo broncas con el chrome y el chromium. Aún no intento lo del `rtweets`.

2021-06-23 06:19 UTC, nepito commented
> > > Las revisiones por mi parte ya quedaron. Por ahí me encontré un paquete, `rtweet`, que revisaré para ver si funciona y agregar los twits de otra manera.
> > 
> > 
> > ¿Ya probaste si te funciona ahora? A mí ya me está corriendo desde el Dockerfile. Pero aun no está andando el _actions_  Supongo que debo de tener alguna falta de ortografía por ahí jajajaja
> 
> El make dentro del contenedor está creando el `index.html`, pero estoy teniendo broncas con el chrome y el chromium. Aún no intento lo del `rtweets`.

Pero si ya está creando el `index.html` ¿para qué quieres el chrome o chromiun?

2021-06-23 20:59 UTC, davidmacer commented
> > > > Las revisiones por mi parte ya quedaron. Por ahí me encontré un paquete, `rtweet`, que revisaré para ver si funciona y agregar los twits de otra manera.
> > > 
> > > 
> > > ¿Ya probaste si te funciona ahora? A mí ya me está corriendo desde el Dockerfile. Pero aun no está andando el _actions_  Supongo que debo de tener alguna falta de ortografía por ahí jajajaja
> > 
> > 
> > El make dentro del contenedor está creando el `index.html`, pero estoy teniendo broncas con el chrome y el chromium. Aún no intento lo del `rtweets`.
> 
> Pero si ya está creando el `index.html` ¿para qué quieres el chrome o chromiun?

No estoy seguro para qué. Por ahí miré, en el Dockerfile, las instrucciones para instalarlos y pensé que son importantes. Además, me saca con un error la primera vez que ejecuto `make docs/index.html`; las siguientes veces ya no marca ese error.

Esta es la primera vez que lo corrí:

![image](https://user-images.githubusercontent.com/7075581/123167056-50dccb80-d433-11eb-96a6-87c72bb46e44.png)

Esta es la segunda vez, inmediatamente después de la anterior:

![image](https://user-images.githubusercontent.com/7075581/123167295-97cac100-d433-11eb-913e-2e1e6748ffa0.png)

2021-06-24 02:33 UTC, nepito commented
lo voy a intentar reproducir. Eso de que la segunda vez sí funciona debe de ser una pista grande 🤔. Muchas gracias @davidmacer por las imágenes. 

La primera es dónde me tronaba a mí también, pero con otro error. ¿Es correcto el `index.html` que genera la segunda vez?

2021-06-24 15:48 UTC, davidmacer commented
> ¿Es correcto el `index.html` que genera la segunda vez?

Eso no lo pude revisar. No supe dónde estaba ese archivo y no pude abirlo para verlo 😅 . Intentaré hacerlo en un rato 😉 .